spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: testdb
---
spring:
  profiles:
    active: dev
    application:
      name: YlbbsApplication
#---
#spring:
#  profiles: dev
#
#server:
#  port: 8081
#
#---
#spring:
#  profiles: prod
#
#server:
#  port: 8080
---
server:
  port: 8666